### ISSUE TITLE
Explanation for the wrong graph

### ISSUE THREAD

**Issue by DRyanMiller** [learn-co-curriculum/dsc-gradient-descent-in-3d#1]
Under the heading Graphs for  dfdx, the explanation states: 

"So as you can see,  δfδxf(1,3)=−6 as shown in the green line in the top left." 

This explanation does not correspond to the graph.

**Comment by lmcm18** [comment]
Fixed. Error was that actual values are x = 3 and y = -1. Thanks @DRyanMiller !
