### ISSUE TITLE
Wrong Answer?

### ISSUE THREAD

**Issue by hpatel530** [learn-co-curriculum/dsc-gradient-descent-in-3d#2]
First, let's understand our plots below -- they may be surprising. Starting at the top left quadrant the graph of the function  𝑓(𝑥,𝑦)  makes sense as when  𝑥=−1  then the function is just  𝑓(𝑦)=−1∗𝑦 .

𝑓(𝑥,𝑦)=(𝑦𝑥2) (x squared)

if we substitute -1  for x, shouldn't this equal 1 * y?

**Comment by jessepisel** [comment]
Thanks for opening this issue @hpatel530 :wave:. You are correct that it should simplify to $f(y) = 1*y$. 

I have made the changes with commit 496ca0e6714cc194493db5cf35c13230b7f20076 and am closing this issue at this time.
